import PageHero from '../../../components/shared/PageHero'
import Container from '../../../components/ui/Container'
import EventRegistrationForm from '../../../components/events/EventRegistrationForm'
import { createAdminClient } from '../../../lib/supabase/admin'
import { buildMetadata } from '../../../lib/seo'
export const metadata=buildMetadata({title:'Free Workshops, Webinars & Campus Events | APTECH Abeokuta',description:'Register for introductory coding workshops, technology career talks, demonstrations and campus open days at APTECH Abeokuta.',path:'/events'})
export const dynamic='force-dynamic'
export default async function EventsRegistrationPage(){let events:{id:string;title:string;starts_at:string}[]=[];try{const db=createAdminClient();const {data}=await db.from('campus_events').select('id,title,starts_at').eq('registration_open',true).gte('starts_at',new Date().toISOString()).order('starts_at').limit(50);events=data||[]}catch{}
 return <><PageHero eyebrow="Learn, explore, connect" title="Free workshops, webinars & campus events" description="Try a coding session, explore technology careers, see a live demonstration or meet our team at an open day." crumbs={[{label:'Home',href:'/'},{label:'Events'}]}/><section className="section"><Container><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] items-start"><div className="grid gap-5"><p className="eyebrow">Your next step into tech</p><h2 className="h-section">Experience learning before you choose a programme.</h2><p style={{color:'var(--color-muted)'}}>Our introductory events are designed for curious beginners, students, parents and anyone exploring digital skills. Register for an upcoming session and tell us what you would like to learn.</p><div className="card p-5"><h3 className="font-semibold">What you can attend</h3><ul className="mt-3 grid gap-2 text-sm"><li>• Introductory coding workshops</li><li>• Technology career talks and demonstrations</li><li>• Programme discovery and admissions Q&A</li><li>• Campus open days and learning experiences</li></ul></div><p className="text-sm" style={{color:'var(--color-muted)'}}>No event listed right now? Please check back soon or <a className="underline" href="/contact">contact our team</a>.</p></div><div><EventRegistrationForm events={events}/></div></div></Container></section></>
}
