'use client'

import { useEffect, useMemo, useState, useTransition } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, Clock3, RotateCcw, Trophy } from 'lucide-react'
import { trackConversionEvent } from '../../lib/conversion-events'
import { captureAttribution, getAttributionSnapshot } from '../../lib/attribution'
import { startChallenge, submitChallenge, captureChallengeLead } from '../../app/(site)/tech-zone/actions'

type Question = { id:string; question:string; options:string[]; skill_area:string; difficulty:string; points:number; sort_order:number; explanation?:string|null }
type Props = { challenge:any; questions:Question[] }

function level(p:number){ if(p>=90)return 'Tech Pro'; if(p>=75)return 'Skilled'; if(p>=50)return 'Explorer'; return 'Beginner' }

export default function ChallengePlayer({challenge,questions}:Props){
  const [clock,setClock]=useState(Date.now()); const [started,setStarted]=useState(false); const [attemptId,setAttemptId]=useState(''); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<Record<string,number>>({}); const [startedAt,setStartedAt]=useState(0); const [result,setResult]=useState<any>(null); const [captureOpen,setCaptureOpen]=useState(false); const [notice,setNotice]=useState(''); const [pending,startTransition]=useTransition()
  useEffect(()=>{ captureAttribution(window.location.search); trackConversionEvent('tech_zone_viewed',{challenge:challenge.slug}); const timer=window.setInterval(()=>setClock(Date.now()),1000); return()=>window.clearInterval(timer) },[challenge.slug])
  const current=questions[index]
  const elapsed=Math.max(0,Math.round((clock-startedAt)/1000))
  const pct=Math.round(((index)/questions.length)*100)
  const attribution=useMemo(()=>getAttributionSnapshot(),[started,result])
  async function begin(){ setNotice(''); const response=await startChallenge({challengeId:challenge.id,sessionId:sessionStorage.getItem('aptech-analytics-session')||undefined,attribution:getAttributionSnapshot()}); if(!response.ok){setNotice(response.message ?? 'We could not start the challenge. Please try again.');return} if(!response.attemptId){setNotice('We could not start the challenge. Please try again.');return} setAttemptId(response.attemptId);setStartedAt(Date.now());setStarted(true);trackConversionEvent('challenge_started',{challenge:challenge.slug,attemptId:response.attemptId}) }
  function answer(i:number){ if(pending)return; const next={...answers,[current.id]:i};setAnswers(next); if(index<questions.length-1){setIndex(index+1);return} startTransition(async()=>{const response=await submitChallenge({attemptId,answers:Object.entries(next).map(([questionId,answerIndex])=>({questionId,answerIndex:Number(answerIndex)})),completionTimeSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000)),attribution:getAttributionSnapshot()}); if(!response.ok || !response.result){setNotice(response.message ?? 'We could not save this result. Please try again.');return} setResult(response.result);trackConversionEvent('challenge_completed',{challenge:challenge.slug,attemptId,score:response.result.score,percentage:response.result.percentage});setCaptureOpen(false);setNotice('');}) }
  if(result){const p=Number(result.percentage);return <div className="tech-challenge tech-challenge--result"><div className="program-finder__result-icon"><Trophy size={22}/></div><p className="eyebrow">Challenge complete</p><h1 className="h-display mt-2">{p}%</h1><h2 className="h-section mt-2">{result.resultLevel}</h2><p className="mt-3" style={{color:'var(--color-body)'}}>{result.message}</p><div className="mt-6 grid grid-cols-2 sm:grid-cols-4 gap-3"><div className="card p-3"><strong>{result.correctAnswers}/{questions.length}</strong><p className="text-xs" style={{color:'var(--color-muted)'}}>Correct</p></div><div className="card p-3"><strong>{result.score}</strong><p className="text-xs" style={{color:'var(--color-muted)'}}>Points</p></div><div className="card p-3"><strong>{result.completionTimeSeconds}s</strong><p className="text-xs" style={{color:'var(--color-muted)'}}>Time</p></div><div className="card p-3"><strong>{result.skillAreas.length}</strong><p className="text-xs" style={{color:'var(--color-muted)'}}>Skill areas</p></div></div>{result.recommendations?.length>0&&<div className="mt-7"><p className="eyebrow">You may enjoy exploring</p><div className="mt-3 flex flex-wrap gap-2">{result.recommendations.map((r:any)=><Link key={r.id} href={'/courses'} className="btn btn-secondary">{r.name}<ArrowRight size={14}/></Link>)}</div></div>}<div className="mt-7 flex flex-wrap gap-3"><button className="btn btn-primary" onClick={()=>setCaptureOpen(true)}>Get my full result</button><Link className="btn btn-secondary" href="/tech-zone">Try another challenge</Link><Link className="btn btn-ghost" href="/admissions?source=tech_challenge">Explore programmes</Link></div>{captureOpen&&<LeadCapture attemptId={attemptId} challenge={challenge} result={result} attribution={attribution} onDone={()=>{setCaptureOpen(false);trackConversionEvent('challenge_result_viewed',{challenge:challenge.slug,attemptId})}}/>}</div>}
  if(!started)return <div className="tech-challenge"><Link href="/tech-zone" className="text-sm inline-flex items-center gap-2" style={{color:'var(--color-muted)'}}><ArrowLeft size={14}/> Tech Zone</Link><p className="eyebrow mt-7">{challenge.category} · {challenge.difficulty}</p><h1 className="h-display mt-2">{challenge.name}</h1><p className="lede mt-3">{challenge.description}</p><div className="mt-6 flex flex-wrap gap-3 text-sm" style={{color:'var(--color-muted)'}}><span>{questions.length} questions</span><span>·</span><span>~{challenge.estimated_minutes} minutes</span></div>{notice&&<p className="mt-5 text-sm" role="alert">{notice}</p>}<button className="btn btn-primary mt-7" onClick={begin}>Start Challenge <ArrowRight size={15}/></button></div>
  return <div className="tech-challenge"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Question {index+1} of {questions.length}</p><div className="mt-2 h-2 rounded-full overflow-hidden" style={{background:'var(--color-paper-alt)'}}><span style={{display:'block',height:'100%',width:`${pct}%`,background:'var(--color-navy-700)'}}/></div></div><div className="tech-challenge__timer"><Clock3 size={15}/>{elapsed}s</div></div><h1 className="h-section mt-7">{current.question}</h1><div className="mt-6 grid gap-3">{current.options.map((o,i)=><button key={o} className="program-finder__option" onClick={()=>answer(i)} disabled={pending}><span className="program-finder__step">{String.fromCharCode(65+i)}</span><span className="program-finder__option-copy">{o}</span><ArrowRight size={16}/></button>)}</div>{notice&&<p className="mt-4 text-sm" role="alert">{notice}</p>}</div>
}

function LeadCapture({attemptId,challenge,result,attribution,onDone}:{attemptId:string;challenge:any;result:any;attribution:any;onDone:()=>void}){
 const [pending,startTransition]=useTransition();const [message,setMessage]=useState('');
 return <form className="mt-8 card p-5 sm:p-6" action={(fd: FormData)=>startTransition(async()=>{const r=await captureChallengeLead(fd);if(!r.ok){setMessage(r.message ?? 'We could not save your result right now.');return}trackConversionEvent('challenge_lead_captured',{challenge:challenge.slug,attemptId});onDone()})}><p className="eyebrow">Save your result</p><h2 className="h-section mt-2">Want your full result and programme recommendations?</h2><p className="text-sm mt-2" style={{color:'var(--color-body)'}}>We'll use your details to send your result and, if relevant, help you explore suitable Aptech programmes.</p><input type="hidden" name="attemptId" value={attemptId}/><input type="hidden" name="attribution" value={JSON.stringify(attribution||{})}/><div className="grid sm:grid-cols-2 gap-4 mt-5"><label className="text-sm">Full Name *<input required name="name" className="input mt-1" maxLength={150}/></label><label className="text-sm">Email<input name="email" type="email" className="input mt-1" maxLength={200}/></label><label className="text-sm">WhatsApp / Phone<input name="phone" className="input mt-1" maxLength={30}/></label><label className="text-sm">Preferred follow-up<select name="communicationPreference" className="input mt-1"><option value="none">No follow-up preference</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="phone">Phone</option></select></label></div><label className="mt-4 flex gap-2 items-start text-sm"><input required type="checkbox" name="consent" value="yes" className="mt-1"/><span>I agree that Aptech Abeokuta may use these details to send my challenge result and relevant programme information.</span></label>{message&&<p className="text-sm mt-3" role="alert">{message}</p>}<button disabled={pending} className="btn btn-primary mt-5">{pending?'Saving…':'Send my result'} <Check size={15}/></button></form>
}
