import Link from 'next/link'
import { ArrowRight, BrainCircuit, Bug, Database, Lightbulb, Trophy } from 'lucide-react'
import Container from '../../../components/ui/Container'
import { getPublicChallenges, type PublicChallenge } from '../../../lib/tech-zone'
import { getPublicContactInfo } from '../../../lib/contact-info-public'
import TechChallenge from '../../../components/home/TechChallenge'
export const metadata = { title: 'Aptech Tech Zone | Challenges & Tech IQ | APTECH Abeokuta', description: 'Test your technology, coding, problem-solving and database skills with interactive Aptech Tech Zone challenges.' }
const icons: Record<string, any> = { quiz: BrainCircuit, debug: Bug, logic: Lightbulb, sql: Database, weekly: Trophy }
export default async function TechZonePage(){const [challenges,{whatsapp}]=await Promise.all([getPublicChallenges(),getPublicContactInfo()]);return <section className="section"><Container className="max-w-6xl"><div className="text-center max-w-3xl mx-auto"><p className="eyebrow">Aptech Tech Zone</p><h1 className="h-display mt-3">Test your tech skills. Challenge yourself. Discover what you’re good at.</h1><p className="lede mt-4">Quick challenges designed to test your problem-solving, coding, digital and technology skills.</p><div className="mt-7"><Link href="#challenges" className="btn btn-primary">Take a Challenge <ArrowRight size={15}/></Link></div></div><div className="mt-12 grid gap-5 lg:grid-cols-2"><div className="card p-5 sm:p-6 lg:col-span-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Existing experience</p><h2 className="h-section mt-2">Tech IQ Challenge</h2><p className="mt-2 text-sm" style={{color:'var(--color-body)'}}>The original five-question Aptech Tech IQ experience is still here — now presented as part of the Tech Zone.</p></div><Link href="/tech-challenge" className="btn btn-secondary">Open Tech IQ <ArrowRight size={15}/></Link></div></div><div id="challenges" className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-5">{challenges.filter(c=>c.slug!=='tech-iq-challenge').map((c: PublicChallenge)=>{const Icon=icons[c.challenge_type]||BrainCircuit;return <article key={c.id} className="card p-5 sm:p-6 flex flex-col"><div className="flex items-start justify-between gap-3"><span className="program-finder__step" aria-hidden="true"><Icon size={18}/></span>{c.is_weekly&&<span className="eyebrow">Weekly</span>}</div><p className="eyebrow mt-5">{c.category} · {c.difficulty}</p><h2 className="text-xl font-bold mt-2">{c.name}</h2><p className="text-sm mt-2 flex-1" style={{color:'var(--color-body)'}}>{c.description}</p><div className="mt-5 flex items-center justify-between gap-3 text-xs" style={{color:'var(--color-muted)'}}><span>{c.question_count} questions</span><span>~{c.estimated_minutes} min</span><Link href={`/tech-zone/${c.slug}`} className="btn btn-primary btn-sm">Start <ArrowRight size={14}/></Link></div></article>})}</div></div><div className="mt-10"><TechChallenge whatsapp={whatsapp}/></div></Container></section>}
