'use server'
import { revalidatePath } from 'next/cache'
import { createAdminClient } from '../../../../lib/supabase/admin'
import { requireCampaignAccess } from '../../../../lib/campaigns'
import { logAudit } from '../../../../lib/audit'
import { slugify } from '../../../../lib/validation'
export type CampaignActionResult = { ok: true; id?: string } | { ok: false; message: string }
function fields(formData: FormData) { return { name:String(formData.get('name')||'').trim(), slug:slugify(String(formData.get('slug')||formData.get('name')||'')), description:String(formData.get('description')||'').trim()||null, status:String(formData.get('status')||'draft'), campaign_type:String(formData.get('campaign_type')||'custom'), start_date:String(formData.get('start_date')||'')||null, end_date:String(formData.get('end_date')||'')||null, programme_id:String(formData.get('programme_id')||'')||null, target_audience:String(formData.get('target_audience')||'').trim()||null, target_location:String(formData.get('target_location')||'').trim()||null, landing_page:String(formData.get('landing_page')||'').trim()||null, primary_cta:String(formData.get('primary_cta')||'').trim()||null, conversion_goal:String(formData.get('conversion_goal')||'enquiry'), source:String(formData.get('source')||'').trim()||null, medium:String(formData.get('medium')||'').trim()||null, campaign_identifier:String(formData.get('campaign_identifier')||'').trim(), headline:String(formData.get('headline')||'').trim()||null, opportunity:String(formData.get('opportunity')||'').trim()||null, notes:String(formData.get('notes')||'').trim()||null } }
function validate(v: ReturnType<typeof fields>) { if(!v.name||v.name.length>180)return'Campaign name is required.'; if(!v.slug)return'A valid campaign slug is required.'; if(!v.campaign_identifier||v.campaign_identifier.length>120)return'Campaign identifier is required.'; if(!['draft','scheduled','active','paused','completed','archived'].includes(v.status))return'Invalid campaign status.'; if(!['google_search','meta_facebook','instagram','whatsapp','organic_search','email','referral','offline','event','school_outreach','programme_specific','general_admissions','seasonal','custom'].includes(v.campaign_type))return'Invalid campaign type.'; if(!['enquiry','advisor_request','application','enrollment'].includes(v.conversion_goal))return'Invalid conversion goal.'; if(v.start_date&&v.end_date&&v.start_date>v.end_date)return'End date must be on or after the start date.'; return null }
export async function createCampaign(_prev:CampaignActionResult,fd:FormData):Promise<CampaignActionResult>{try{const staff=await requireCampaignAccess('create');const v=fields(fd),problem=validate(v);if(problem)return{ok:false,message:problem};const admin=createAdminClient();const{data,error}=await admin.from('campaigns').insert({...v,created_by:staff.id,updated_by:staff.id}).select('id').single();if(error){if(error.code==='23505')return{ok:false,message:'The campaign slug or identifier is already in use.'};console.error(error);return{ok:false,message:'Could not create the campaign.'}}await logAudit(admin,{userId:staff.id,action:'campaign.created',entity:'campaign',entityId:data.id,metadata:{name:v.name}});revalidatePath('/admin/campaigns');revalidatePath(`/campaigns/${v.slug}`);return{ok:true,id:data.id}}catch(e){console.error(e);return{ok:false,message:'You do not have permission to create campaigns.'}}}
export async function updateCampaign(_prev:CampaignActionResult,fd:FormData):Promise<CampaignActionResult>{try{const staff=await requireCampaignAccess('edit');const id=String(fd.get('id')||'');if(!id)return{ok:false,message:'Missing campaign.'};const v=fields(fd),problem=validate(v);if(problem)return{ok:false,message:problem};const admin=createAdminClient();const{error}=await admin.from('campaigns').update({...v,updated_by:staff.id}).eq('id',id);if(error){if(error.code==='23505')return{ok:false,message:'The campaign slug or identifier is already in use.'};return{ok:false,message:'Could not update the campaign.'}}await logAudit(admin,{userId:staff.id,action:'campaign.updated',entity:'campaign',entityId:id,metadata:{name:v.name,status:v.status}});revalidatePath('/admin/campaigns');revalidatePath(`/admin/campaigns/${id}`);revalidatePath(`/campaigns/${v.slug}`);return{ok:true,id}}catch(e){console.error(e);return{ok:false,message:'You do not have permission to update campaigns.'}}}
export async function deleteCampaign(_prev:CampaignActionResult,fd:FormData):Promise<CampaignActionResult>{try{const staff=await requireCampaignAccess('delete');const id=String(fd.get('id')||'');if(!id)return{ok:false,message:'Missing campaign.'};const admin=createAdminClient();const{data:existing}=await admin.from('campaigns').select('slug,name').eq('id',id).maybeSingle();const{error}=await admin.from('campaigns').delete().eq('id',id);if(error)return{ok:false,message:'Could not delete the campaign. Archive campaigns with attributed leads instead.'};await logAudit(admin,{userId:staff.id,action:'campaign.deleted',entity:'campaign',entityId:id,metadata:{name:existing?.name}});revalidatePath('/admin/campaigns');return{ok:true}}catch(e){console.error(e);return{ok:false,message:'You do not have permission to delete campaigns.'}}}
