'use client'
import { useActionState } from 'react'
import { createCampaign, updateCampaign, type CampaignActionResult } from '../../app/admin/(dashboard)/campaigns/actions'
import type { Campaign, Programme } from '../../types/db'
const initial:CampaignActionResult={ok:true};const types=[['google_search','Google Search'],['meta_facebook','Meta / Facebook'],['instagram','Instagram'],['whatsapp','WhatsApp'],['organic_search','Organic Search'],['email','Email'],['referral','Referral'],['offline','Offline'],['event','Event'],['school_outreach','School outreach'],['programme_specific','Programme-specific'],['general_admissions','General admissions'],['seasonal','Seasonal'],['custom','Custom']];const goals=[['enquiry','Enquiry'],['advisor_request','Advisor request'],['application','Application'],['enrollment','Enrollment']];const statuses=[['draft','Draft'],['scheduled','Scheduled'],['active','Active'],['paused','Paused'],['completed','Completed'],['archived','Archived']]
export default function CampaignForm({campaign,programmes}:{campaign?:Campaign;programmes:Programme[]}){const action=campaign?updateCampaign:createCampaign;const[state,formAction]=useActionState(action,initial);return <form action={formAction} className="grid gap-5">{campaign&&<input type="hidden" name="id" value={campaign.id}/>} {!state.ok&&<div className="form-alert form-alert-error">{state.message}</div>}<div className="grid grid-cols-1 md:grid-cols-2 gap-5">
<label className="grid gap-1"><span className="field-label">Campaign name *</span><input name="name" className="field-input" defaultValue={campaign?.name} required/></label><label className="grid gap-1"><span className="field-label">Campaign identifier *</span><input name="campaign_identifier" className="field-input" defaultValue={campaign?.campaign_identifier} placeholder="e.g. adse-oct-2026" required/></label>
<label className="grid gap-1"><span className="field-label">Slug</span><input name="slug" className="field-input" defaultValue={campaign?.slug} placeholder="Generated from name if blank"/></label><label className="grid gap-1"><span className="field-label">Status</span><select name="status" className="field-select" defaultValue={campaign?.status||'draft'}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
<label className="grid gap-1"><span className="field-label">Campaign type</span><select name="campaign_type" className="field-select" defaultValue={campaign?.campaign_type||'custom'}>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="grid gap-1"><span className="field-label">Conversion goal</span><select name="conversion_goal" className="field-select" defaultValue={campaign?.conversion_goal||'enquiry'}>{goals.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
<label className="grid gap-1"><span className="field-label">Target programme</span><select name="programme_id" className="field-select" defaultValue={campaign?.programme_id||''}><option value="">All programmes</option>{programmes.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="grid gap-1"><span className="field-label">Target audience</span><input name="target_audience" className="field-input" defaultValue={campaign?.target_audience||''}/></label>
<label className="grid gap-1"><span className="field-label">Target location</span><input name="target_location" className="field-input" defaultValue={campaign?.target_location||''}/></label><label className="grid gap-1"><span className="field-label">Start date</span><input name="start_date" type="date" className="field-input" defaultValue={campaign?.start_date||''}/></label><label className="grid gap-1"><span className="field-label">End date</span><input name="end_date" type="date" className="field-input" defaultValue={campaign?.end_date||''}/></label>
<label className="grid gap-1"><span className="field-label">Source</span><input name="source" className="field-input" defaultValue={campaign?.source||''} placeholder="google, instagram…"/></label><label className="grid gap-1"><span className="field-label">Medium</span><input name="medium" className="field-input" defaultValue={campaign?.medium||''} placeholder="cpc, social, email…"/></label>
<label className="grid gap-1 md:col-span-2"><span className="field-label">Landing page</span><input name="landing_page" className="field-input" defaultValue={campaign?.landing_page||''} placeholder="/campaigns/your-slug"/></label><label className="grid gap-1 md:col-span-2"><span className="field-label">Headline</span><input name="headline" className="field-input" defaultValue={campaign?.headline||''}/></label>
<label className="grid gap-1 md:col-span-2"><span className="field-label">Problem / opportunity</span><textarea name="opportunity" className="field-input min-h-24" defaultValue={campaign?.opportunity||''}/></label><label className="grid gap-1"><span className="field-label">Primary CTA</span><input name="primary_cta" className="field-input" defaultValue={campaign?.primary_cta||''} placeholder="Talk to an Advisor"/></label><label className="grid gap-1"><span className="field-label">Description</span><textarea name="description" className="field-input min-h-24" defaultValue={campaign?.description||''}/></label><label className="grid gap-1 md:col-span-2"><span className="field-label">Notes</span><textarea name="notes" className="field-input min-h-24" defaultValue={campaign?.notes||''}/></label></div><button className="btn btn-primary justify-self-start" type="submit">{campaign?'Save campaign':'Create campaign'}</button></form>}
