-- Rollback for migration 0021. Restores the original 0004/0019 values, but only
-- where a field still holds the text 0021 wrote (so later staff edits survive).
begin;

update insights set
  content = case when md5(content) = '9fd31cb7d8f0feafa84fe2c032e81e25' then
$body$<p>Software development remains one of the most accessible tech careers to break into without a traditional computer science degree, because employers in Nigeria's fast-growing tech sector generally care more about what you can build than which certificate hangs on your wall.</p><p>Start with programming fundamentals — variables, control flow, functions and basic data structures — in one language before spreading yourself across many. Most learners do this with a general-purpose language like Python or Java, or go straight into web fundamentals with HTML, CSS and JavaScript if front-end work appeals to you.</p><p>From there, pick a specialisation: front-end (React and modern JavaScript), back-end (a language like Java, C# or Python paired with databases and APIs), or full-stack. Structured programmes such as the Advanced Diploma in Software Engineering are built specifically to take a beginner through this progression in order, rather than leaving you to guess which topic to learn next.</p><p>A portfolio matters more than most beginners expect. Two or three well-documented projects — even simple ones — that you can explain in an interview will do more for your job prospects than a long list of tutorials watched. Building real, working software, including the debugging and testing that goes with it, is what separates someone who has 'learned about' programming from someone who can actually do the job.</p><p>Finally, treat the learning curve as ongoing. The tools and frameworks used in professional development change every few years; the constant is a solid grasp of fundamentals and the habit of learning independently once you are employed.</p>$body$ else content end,
  seo_title = case when seo_title = 'How to Become a Software Developer in Nigeria: Step-by-Step' then 'How to Become a Software Developer in Nigeria | APTECH Abeokuta' else seo_title end,
  seo_description = case when seo_description = 'A step-by-step path to becoming a software developer in Nigeria: learn one language, pick a specialisation, master Git and SQL, and build a portfolio.' then 'A practical look at the skills, learning path and portfolio work that matter for landing a software development role in Nigeria today.' else seo_description end
where slug = 'how-to-become-a-software-developer-in-nigeria'
  and (md5(content) = '9fd31cb7d8f0feafa84fe2c032e81e25'
    or seo_title = 'How to Become a Software Developer in Nigeria: Step-by-Step'
    or seo_description = 'A step-by-step path to becoming a software developer in Nigeria: learn one language, pick a specialisation, master Git and SQL, and build a portfolio.');

update insights set
  content = case when md5(content) = '3b60262742aa6a2eb8cafeb5f9dac4e7' then
$body$<p>It's tempting to chase whichever technology is trending, but employers consistently value a smaller set of durable skills over flashy ones.</p><p>Version control (Git) is non-negotiable — almost every professional software team uses it daily, yet many self-taught learners skip it entirely. Basic command-line comfort, understanding how the operating system you work on actually functions, and being able to read someone else's code are similarly underrated but constantly used.</p><p>On the data side, even a working knowledge of SQL and how databases are structured will serve you regardless of which specific role you end up in — from software development to data analysis to IT support.</p><p>Communication is the most overlooked "technical" skill. Being able to explain a bug, write a clear commit message, or describe a problem to a non-technical colleague is something structured, instructor-led training environments are specifically designed to build through project work and presentations, in a way that solo online learning rarely forces you to practise.</p>$body$ else content end,
  seo_title = case when seo_title = 'IT Skills Students Should Learn Before Graduating' then 'IT Skills Students Should Learn | APTECH Abeokuta' else seo_title end,
  seo_description = case when seo_description = 'Eight durable IT skills worth learning before you graduate, from Git and SQL to networking basics, plus how to build each one with hands-on practice.' then 'The practical, employer-relevant IT skills that separate job-ready graduates from those who struggle to find their first tech role.' else seo_description end
where slug = 'it-skills-students-should-learn'
  and (md5(content) = '3b60262742aa6a2eb8cafeb5f9dac4e7'
    or seo_title = 'IT Skills Students Should Learn Before Graduating'
    or seo_description = 'Eight durable IT skills worth learning before you graduate, from Git and SQL to networking basics, plus how to build each one with hands-on practice.');

update insights set
  title = case when title = 'What Is Cybersecurity? A Plain-Language Guide for Beginners' then 'What Is Cybersecurity, and Why Does It Matter Right Now?' else title end,
  short_description = case when short_description = 'A plain-language introduction to what cybersecurity is, the main areas of the field, and the skills and learning path that lead into it.' then 'A plain-language introduction to cybersecurity fundamentals, common career entry points, and why demand for these skills keeps growing.' else short_description end,
  content = case when md5(content) = 'cc27cf05624772536ffa24825fe927fe' then
$body$<p>Cybersecurity is the practice of protecting computer systems, networks and data from unauthorised access, damage or theft. As more of daily life, business and government moves online, the attack surface — every place a system could be exploited — keeps expanding, and so does the need for people who understand how to defend it.</p><p>Entry points into the field vary. Some start from a networking and systems administration background (understanding how networks are built before learning how to defend them), which is why network-focused certifications like CompTIA Network+ and CCNA are often a practical first step before specialising into security-specific certifications.</p><p>Others come from software, learning how vulnerabilities appear in code and how to test for them — the basis of ethical hacking and penetration testing, often validated by certifications such as CEH.</p><p>Whichever path you take, the fundamentals are consistent: understand how systems normally work before learning how they can be broken, and build hands-on experience in a lab environment rather than relying on theory alone.</p>$body$ else content end,
  seo_title = case when seo_title = 'What Is Cybersecurity? A Beginner''s Guide | APTECH Abeokuta' then 'What Is Cybersecurity and Why It Matters | APTECH Abeokuta' else seo_title end,
  seo_description = case when seo_description = 'What cybersecurity is, the main areas of the field, and the networking, systems and ethical-hacking skills that lead into a cybersecurity career.' then 'A plain-language introduction to cybersecurity fundamentals, common career entry points, and why demand for these skills keeps growing.' else seo_description end
where slug = 'what-is-cybersecurity-and-why-it-matters'
  and (title = 'What Is Cybersecurity? A Plain-Language Guide for Beginners'
    or short_description = 'A plain-language introduction to what cybersecurity is, the main areas of the field, and the skills and learning path that lead into it.'
    or md5(content) = 'cc27cf05624772536ffa24825fe927fe'
    or seo_title = 'What Is Cybersecurity? A Beginner''s Guide | APTECH Abeokuta'
    or seo_description = 'What cybersecurity is, the main areas of the field, and the networking, systems and ethical-hacking skills that lead into a cybersecurity career.');

update insights set
  content = case when md5(content) = '7c95d41021e43390a457559bfc6daeec' then
$body$<p>The terms get used almost interchangeably, but the actual work differs. Data analytics is primarily about examining existing data to answer specific business questions — using tools like Excel, SQL and visualisation platforms such as Power BI or Tableau to spot patterns and report on what has already happened.</p><p>Data science goes further, often building predictive models using statistics, programming (typically Python or R) and machine learning to forecast what is likely to happen next, or to automate a decision that would otherwise require human judgement.</p><p>In practice, most people starting out benefit from learning analytics fundamentals first — spreadsheet and SQL fluency, basic statistics, and a visualisation tool — before layering on the programming and machine learning skills that data science requires. Programmes structured around a shared foundation before branching into specialisation, such as Smart Pro's Foundation-then-specialisation model, follow this same logic deliberately.</p>$body$ else content end,
  seo_title = case when seo_title = 'Data Analytics vs Data Science: Differences Explained' then 'Data Analytics vs Data Science | APTECH Abeokuta' else seo_title end,
  seo_description = case when seo_description = 'Data analytics explains what happened; data science builds models to predict what comes next. Compare the work, tools and best starting point for beginners.' then 'Data analytics and data science are closely related but differ in day-to-day work, tools and starting points for beginners.' else seo_description end
where slug = 'data-analytics-vs-data-science'
  and (md5(content) = '7c95d41021e43390a457559bfc6daeec'
    or seo_title = 'Data Analytics vs Data Science: Differences Explained'
    or seo_description = 'Data analytics explains what happened; data science builds models to predict what comes next. Compare the work, tools and best starting point for beginners.');

update insights set
  title = case when title = 'Study Tips for Learning to Code: Habits That Help Beginners' then 'Study Tips for Learning to Code (That Actually Work)' else title end,
  short_description = case when short_description = 'Common mistakes new programming students make, and practical habits that make the learning curve less painful.' then 'Common mistakes new programming students make, and habits that make the learning curve noticeably less painful.' else short_description end,
  content = case when md5(content) = '04d5d0d82a2c5506f9c417405566c5da' then
$body$<p>The single biggest mistake new coding students make is passively watching or reading instead of typing code themselves. Programming is a skill you build through repetition and mistakes, not one you absorb by observation — type out every example yourself, even ones that look simple.</p><p>Expect to be stuck. Getting an error message, not knowing why your code isn't working, and spending twenty minutes on a bug that turns out to be a missing comma is completely normal, not a sign you're bad at this. Learning to read error messages calmly and methodically is itself a skill worth practising.</p><p>Build things you actually care about as soon as the fundamentals allow it. A small project of your own choosing will teach you more, and keep you more motivated, than the tenth generic tutorial exercise.</p><p>Finally, don't isolate yourself. Studying alongside classmates or in a cohort — asking questions out loud, explaining a concept to someone else, comparing approaches — consistently produces better outcomes than studying entirely alone, which is one of the main practical advantages of structured, instructor-led training over self-study.</p>$body$ else content end,
  seo_title = case when seo_title = 'Study Tips for Learning to Code: Habits for Beginners' then 'Study Tips for Learning to Code | APTECH Abeokuta' else seo_title end,
  seo_description = case when seo_description = 'Practical study habits for beginner programmers: type the code yourself, read error messages, build small projects, ask good questions and learn with others.' then 'Common mistakes new programming students make, and habits that make the learning curve noticeably less painful.' else seo_description end
where slug = 'study-tips-for-learning-to-code'
  and (title = 'Study Tips for Learning to Code: Habits That Help Beginners'
    or short_description = 'Common mistakes new programming students make, and practical habits that make the learning curve less painful.'
    or md5(content) = '04d5d0d82a2c5506f9c417405566c5da'
    or seo_title = 'Study Tips for Learning to Code: Habits for Beginners'
    or seo_description = 'Practical study habits for beginner programmers: type the code yourself, read error messages, build small projects, ask good questions and learn with others.');

update insights set
  content = case when md5(content) = '0381c92337d04a4896a6fe7b0afef6a2' then
$body$<p>A short, focused course — a few weeks on a specific tool or skill like Advanced Excel, a specific programming language, or a particular certification track — makes sense when you already have a general direction and need one concrete, immediately-usable skill added to what you know.</p><p>A longer diploma-style programme makes more sense when you are starting from very little existing background and want a structured path that builds fundamentals first, then specialises — the kind of progression the Advanced Diploma in Software Engineering and Aptech Certified Network Specialist programmes are built around.</p><p>If you're unsure, our own Program Finder tool on the homepage is a quick way to get a starting recommendation based on your interests and how much time you can commit, and admissions staff can talk through your specific situation in more detail.</p>$body$ else content end,
  seo_description = case when seo_description = 'Short course or diploma? Compare scope, time commitment and starting point, with real examples from APTECH Abeokuta''s course lengths and programmes.' then 'A short, focused course and a longer diploma programme solve different problems. How to work out which one fits your situation.' else seo_description end
where slug = 'choosing-between-short-course-and-diploma'
  and (md5(content) = '0381c92337d04a4896a6fe7b0afef6a2'
    or seo_description = 'Short course or diploma? Compare scope, time commitment and starting point, with real examples from APTECH Abeokuta''s course lengths and programmes.');

commit;
