'use server'
import { revalidatePath } from 'next/cache'
import { createAdminClient } from '../../../../lib/supabase/admin'
import { logAudit } from '../../../../lib/audit'
import { requireChallengeAccess } from '../../../../lib/tech-zone'
function str(fd:FormData,k:string){return String(fd.get(k)||'').trim()}
function json<T>(v:string,f:T):T{try{return JSON.parse(v) as T}catch{return f}}
export async function saveChallenge(fd:FormData){try{const staff=await requireChallengeAccess(str(fd,'id')?'edit':'create');const admin=createAdminClient();const id=str(fd,'id');const values:any={name:str(fd,'name'),slug:str(fd,'slug'),description:str(fd,'description'),category:str(fd,'category')||'Technology',difficulty:str(fd,'difficulty')||'beginner',estimated_minutes:Math.max(1,Math.min(60,Number(fd.get('estimated_minutes'))||3)),challenge_type:str(fd,'challenge_type')||'quiz',status:str(fd,'status')||'draft',is_featured:fd.get('is_featured')==='on',is_weekly:fd.get('is_weekly')==='on',start_date:str(fd,'start_date')||null,end_date:str(fd,'end_date')||null,sort_order:Number(fd.get('sort_order'))||0,scoring_config:{},recommendation_rules:json(str(fd,'recommendation_rules'),'[]'),updated_by:staff.id};
const rawScoring=str(fd,'scoring_config')||'{}';try{const parsed=JSON.parse(rawScoring);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('not an object');values.scoring_config=parsed}catch{return{ok:false,message:'Scoring / dataset JSON is not valid. Nothing was saved.'}}
if(fd.has('playground_kind')){const kind=str(fd,'playground_kind');values.playground_kind=['weekly','detective','speed_round','data_detective','daily'].includes(kind)?kind:null;const cat=str(fd,'detective_category');values.detective_category=['code','web','data','sql','cyber'].includes(cat)?cat:null;const tl=Number(fd.get('time_limit_seconds'));values.time_limit_seconds=Number.isFinite(tl)&&tl>=10?Math.min(3600,Math.round(tl)):null;const sd=Number(fd.get('streak_day'));values.streak_day=Number.isInteger(sd)&&sd>=1&&sd<=7?sd:null}
if(!id)values.created_by=staff.id;if(!values.name||!values.slug)return{ok:false,message:'Name and slug are required.'};const result=id?await admin.from('tech_challenges').update(values).eq('id',id).select('id').single():await admin.from('tech_challenges').insert(values).select('id').single();if(result.error)throw result.error;await logAudit(admin,{userId:staff.id,action:id?'challenge.updated':'challenge.created',entity:'tech_challenge',entityId:result.data.id,metadata:{name:values.name}});revalidatePath('/admin/challenges');revalidatePath('/tech-zone');revalidatePath(`/tech-zone/${values.slug}`);revalidatePath('/tech-playground','layout');return{ok:true,id:result.data.id}}catch(e){console.error(e);return{ok:false,message:'Could not save the challenge.'}}}
export async function saveQuestion(fd:FormData){try{const staff=await requireChallengeAccess('edit');const admin=createAdminClient();const id=str(fd,'id');const challengeId=str(fd,'challenge_id');const values:any={challenge_id:challengeId,question:str(fd,'question'),options:json(str(fd,'options'),'[]'),correct_answer:Number(fd.get('correct_answer')),explanation:str(fd,'explanation')||null,skill_area:str(fd,'skill_area')||'Technology Fundamentals',difficulty:str(fd,'difficulty')||'beginner',points:Math.max(1,Math.min(100,Number(fd.get('points'))||10)),sort_order:Number(fd.get('sort_order'))||0};if(!challengeId||!values.question||!Array.isArray(values.options)||values.correct_answer<0||values.correct_answer>=values.options.length)return{ok:false,message:'Question, options and a valid correct answer are required.'};const r=id?await admin.from('tech_challenge_questions').update(values).eq('id',id).select('id').single():await admin.from('tech_challenge_questions').insert(values).select('id').single();if(r.error)throw r.error;await logAudit(admin,{userId:staff.id,action:id?'challenge.question_updated':'challenge.question_created',entity:'tech_challenge_question',entityId:r.data.id,metadata:{challengeId}});revalidatePath(`/admin/challenges/${challengeId}`);revalidatePath('/tech-zone');revalidatePath('/tech-playground','layout');return{ok:true,id:r.data.id}}catch(e){console.error(e);return{ok:false,message:'Could not save the question.'}}}
export async function deleteQuestion(fd:FormData){try{const staff=await requireChallengeAccess('delete');const admin=createAdminClient();const id=str(fd,'id');const challengeId=str(fd,'challenge_id');await admin.from('tech_challenge_questions').delete().eq('id',id);await logAudit(admin,{userId:staff.id,action:'challenge.question_deleted',entity:'tech_challenge_question',entityId:id,metadata:{challengeId}});revalidatePath(`/admin/challenges/${challengeId}`);return{ok:true}}catch(e){console.error(e);return{ok:false,message:'Could not delete the question.'}}}

export async function setAttemptHidden(fd:FormData){try{const staff=await requireChallengeAccess('edit');const admin=createAdminClient();const id=str(fd,'id');const hidden=str(fd,'hidden')==='true';const{error}=await admin.from('tech_challenge_attempts').update({is_hidden:hidden}).eq('id',id);if(error)throw error;await logAudit(admin,{userId:staff.id,action:hidden?'challenge.attempt_hidden':'challenge.attempt_unhidden',entity:'tech_challenge_attempt',entityId:id,metadata:{}});revalidatePath('/admin/challenges/leaderboard');revalidatePath('/tech-playground','layout');return{ok:true}}catch(e){console.error(e);return{ok:false}}}
export async function setParticipantHidden(fd:FormData){try{const staff=await requireChallengeAccess('edit');const admin=createAdminClient();const id=str(fd,'id');const hidden=str(fd,'hidden')==='true';const{error}=await admin.from('playground_participants').update({is_hidden:hidden}).eq('id',id);if(error)throw error;await logAudit(admin,{userId:staff.id,action:hidden?'playground.participant_hidden':'playground.participant_unhidden',entity:'playground_participant',entityId:id,metadata:{}});revalidatePath('/admin/challenges/leaderboard');revalidatePath('/tech-playground','layout');return{ok:true}}catch(e){console.error(e);return{ok:false}}}
